/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions_.$slug'
import { Route as ProductsMaaxStudioRouteImport } from './routes/products_.maax-studio'
import { Route as ProductsLyraRouteImport } from './routes/products_.lyra'
import { Route as ApiPublicWebVitalsRouteImport } from './routes/api/public/web-vitals'
import { Route as ApiPublicCtaEventsRouteImport } from './routes/api/public/cta-events'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions_/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMaaxStudioRoute = ProductsMaaxStudioRouteImport.update({
  id: '/products_/maax-studio',
  path: '/products/maax-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLyraRoute = ProductsLyraRouteImport.update({
  id: '/products_/lyra',
  path: '/products/lyra',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebVitalsRoute = ApiPublicWebVitalsRouteImport.update({
  id: '/api/public/web-vitals',
  path: '/api/public/web-vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCtaEventsRoute = ApiPublicCtaEventsRouteImport.update({
  id: '/api/public/cta-events',
  path: '/api/public/cta-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/start': typeof StartRoute
  '/products/lyra': typeof ProductsLyraRoute
  '/products/maax-studio': typeof ProductsMaaxStudioRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/api/public/cta-events': typeof ApiPublicCtaEventsRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/start': typeof StartRoute
  '/products/lyra': typeof ProductsLyraRoute
  '/products/maax-studio': typeof ProductsMaaxStudioRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/api/public/cta-events': typeof ApiPublicCtaEventsRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/start': typeof StartRoute
  '/products_/lyra': typeof ProductsLyraRoute
  '/products_/maax-studio': typeof ProductsMaaxStudioRoute
  '/solutions_/$slug': typeof SolutionsSlugRoute
  '/api/public/cta-events': typeof ApiPublicCtaEventsRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/products'
    | '/research'
    | '/sitemap.xml'
    | '/solutions'
    | '/start'
    | '/products/lyra'
    | '/products/maax-studio'
    | '/solutions/$slug'
    | '/api/public/cta-events'
    | '/api/public/web-vitals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/products'
    | '/research'
    | '/sitemap.xml'
    | '/solutions'
    | '/start'
    | '/products/lyra'
    | '/products/maax-studio'
    | '/solutions/$slug'
    | '/api/public/cta-events'
    | '/api/public/web-vitals'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/products'
    | '/research'
    | '/sitemap.xml'
    | '/solutions'
    | '/start'
    | '/products_/lyra'
    | '/products_/maax-studio'
    | '/solutions_/$slug'
    | '/api/public/cta-events'
    | '/api/public/web-vitals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  StartRoute: typeof StartRoute
  ProductsLyraRoute: typeof ProductsLyraRoute
  ProductsMaaxStudioRoute: typeof ProductsMaaxStudioRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  ApiPublicCtaEventsRoute: typeof ApiPublicCtaEventsRoute
  ApiPublicWebVitalsRoute: typeof ApiPublicWebVitalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/$slug': {
      id: '/solutions_/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/maax-studio': {
      id: '/products_/maax-studio'
      path: '/products/maax-studio'
      fullPath: '/products/maax-studio'
      preLoaderRoute: typeof ProductsMaaxStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/lyra': {
      id: '/products_/lyra'
      path: '/products/lyra'
      fullPath: '/products/lyra'
      preLoaderRoute: typeof ProductsLyraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/web-vitals': {
      id: '/api/public/web-vitals'
      path: '/api/public/web-vitals'
      fullPath: '/api/public/web-vitals'
      preLoaderRoute: typeof ApiPublicWebVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cta-events': {
      id: '/api/public/cta-events'
      path: '/api/public/cta-events'
      fullPath: '/api/public/cta-events'
      preLoaderRoute: typeof ApiPublicCtaEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  StartRoute: StartRoute,
  ProductsLyraRoute: ProductsLyraRoute,
  ProductsMaaxStudioRoute: ProductsMaaxStudioRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  ApiPublicCtaEventsRoute: ApiPublicCtaEventsRoute,
  ApiPublicWebVitalsRoute: ApiPublicWebVitalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
